options:
  logging: CLOUD_LOGGING_ONLY
serviceAccount: cloud-build@sibr-market.iam.gserviceaccount.com


steps:
# STEP 0: Check the commit message.
- name: 'gcr.io/cloud-builders/git'
  id: 'Check-commit-message'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    commit_message=$(git log -1 --pretty=%B "${COMMIT_SHA}")
    if [[ ! "$commit_message" =~ "gcloud build" ]]; then
      echo "Keyword 'gcloud build' is missing. Failing build."
      exit 1
    else
      echo "Keyword found. Proceeding with build."
    fi


## =========== AGENT =================
# STEP 1: Build the Docker container
- name: 'gcr.io/cloud-builders/docker'
  id: 'build-agent'
  waitFor: ['Check-commit-message']
  args:
    - 'build'
    - '-t'
    - 'europe-west1-docker.pkg.dev/sibr-market/sibr-market-repo/agent:$COMMIT_SHA'
    - './agent'

# STEP 2: Push the Docker container
- name: 'gcr.io/cloud-builders/docker'
  id: "push-agent"
  waitFor: ['build-agent']
  args:
    - 'push'
    - 'europe-west1-docker.pkg.dev/sibr-market/sibr-market-repo/agent:$COMMIT_SHA'

# STEP 3: Deploy to Cloud Run
- name: 'gcr.io/google.com/cloudsdk/cloud-sdk'
  id: 'deploy-gcloud-run-agent'
  waitFor: ['push-agent']
  args:
    - gcloud
    - run
    - deploy
    - 'agent'
    - --image=europe-west1-docker.pkg.dev/sibr-market/sibr-market-repo/agent:$COMMIT_SHA
    - --region=europe-west1
    - --platform=managed
    - --allow-unauthenticated

## =========== API =================
## STEP 1: Build the Docker container
#- name: 'gcr.io/cloud-builders/docker'
#  id: 'build-api'
#  waitFor: ['Check-commit-message']
#  args:
#    - 'build'
#    - '-t'
#    - 'europe-west1-docker.pkg.dev/sibr-market/sibr-market-repo/api:$COMMIT_SHA'
#    - './api'

## STEP 2: Push the Docker container
#- name: 'gcr.io/cloud-builders/docker'
#  id: "push-api"
#  waitFor: ['build-api']
#  args:
#    - 'push'
#    - 'europe-west1-docker.pkg.dev/sibr-market/sibr-market-repo/api:$COMMIT_SHA'


## STEP 3: Deploy to Cloud Run
#- name: 'gcr.io/google.com/cloudsdk/cloud-sdk'
#  id: 'deploy-gcloud-run-api'
#  waitFor: ['push-api']
#  args:
#    - gcloud
#    - run
#    - deploy
#    - 'api'
#    - --image=europe-west1-docker.pkg.dev/sibr-market/sibr-market-repo/api:$COMMIT_SHA
#    - --region=europe-west1
#    - --platform=managed
#    - --allow-unauthenticated

images:
- 'europe-west1-docker.pkg.dev/sibr-market/sibr-market-repo/agent:$COMMIT_SHA'
- 'europe-west1-docker.pkg.dev/sibr-market/sibr-market-repo/api:$COMMIT_SHA'